---
title: "IA_script"
author: "KV"
date: "2025-03-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ade4)
library(dplyr)
library(tidyr)
```

```{r}
Seuillage<-read.csv("seuillage_results.csv", header=T)
Sam2<-read.csv("sam2_results.csv", header=T)

```

```{r}
plot(Seuillage$IoU, type="l", col="red", lwd=2, 
     xlab="Index", ylab="IoU", 
     main="Comparaison des valeurs d'IoU",
     ylim=c(min(c(Seuillage$IoU, Sam2$IoU)), max(c(Seuillage$IoU, Sam2$IoU)))) 

lines(Sam2$IoU, col="blue", lwd=2)  # Ajout de la seconde courbe en bleu
legend("topright", legend=c("Seuillage", "Sam2"), 
       col=c("red", "blue"), lwd=2)
```

```{r}
Seuillage$Method <- "Seuillage"
Sam2$Method <- "Sam2"

data_big <- bind_rows(Seuillage, Sam2) %>%
  mutate(num = row_number())
```


```{r}
#comparaison IoU
plot_IoU= ggplot(data_big, aes(x=num, y=IoU, color=Method, group=Method)) +
  geom_violin() +  
  theme_minimal() + 
  labs(title="Comparaison des valeurs d'IoU",
       x="Index",
       y="IoU",
       color="Méthode") +
  scale_color_manual(values=c("red", "blue")) + 
  theme(text = element_text(size=14))  
```

```{r}
#Comparaison Precision
plot_Precision= ggplot(data_big, aes(x=num, y=Precision, color=Method, group=Method)) +
  geom_violin() +  
  theme_minimal() + 
  labs(title="Comparaison des valeurs Precision",
       x="Index",
       y="Précision",
       color="Méthode") +
  scale_color_manual(values=c("red", "blue")) + 
  theme(text = element_text(size=14))  
```

```{r}
#Comparaison Rapelle
plot_Recall= ggplot(data_big, aes(x=num, y=Recall, color=Method, group=Method)) +
  geom_violin() +  
  theme_minimal() + 
  labs(title="Comparaison des valeurs Recall",
       x="Index",
       y="Recall",
       color="Méthode") +
  scale_color_manual(values=c("red", "blue")) + 
  theme(text = element_text(size=14))  
```

```{r}
#Comparaison F1_Score
plot_F1Score= ggplot(data_big, aes(x=num, y=F1_Score, color=Method, group=Method)) +
  geom_violin() +  
  theme_minimal() + 
  labs(title="Comparaison des valeurs F1-Score",
       x="Index",
       y="F1-Score",
       color="Méthode") +
  scale_color_manual(values=c("red", "blue")) + 
  theme(text = element_text(size=14))  
```

```{r}
par(mfrow= c(2,2))
plot_IoU
plot_Precision
plot_Recall
plot_F1Score
```
